export const playlistCategories = [
    {
        code: 'all',
        name: "全部",
        enable: true,
        bigCat: 'static',
    },
    {
        code: 'recommendPlaylists',
        name: "推荐歌单",
        enable: true,
        bigCat: 'static',
    },
    {
        code: 'premiumPlaylist',
        name: "精品歌单",
        enable: true,
        bigCat: 'static',
    },
    {
        code: 'official',
        name: "官方",
        enable: true,
        bigCat: 'static',
    },
    {
        code: 'rankingList',
        name: "排行榜",
        enable: true,
        bigCat: 'static',
    },
    {
        code: 'mandarin',
        name: "华语",
        enable: false,
        bigCat: 'language',
    },
    {
        code: 'western',
        name: "欧美",
        enable: true,
        bigCat: 'language',
    },
    {
        code: 'japanese',
        name: "日语",
        enable: false,
        bigCat: 'language',
    },
    {
        code: 'korean',
        name: "韩语",
        enable: false,
        bigCat: 'language',
    },
    {
        code: 'cantonese',
        name: "粤语",
        enable: false,
        bigCat: 'language',
    },
    {
        code: 'popular',
        name: "流行",
        enable: true,
        bigCat: 'style',
    },
    {
        code: 'rock',
        name: "摇滚",
        enable: true,
        bigCat: 'style',
    },
    {
        code: 'ballad',
        name: "民谣",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'electron',
        name: "电子",
        enable: true,
        bigCat: 'style',
    },
    {
        code: 'danceMusic',
        name: "舞曲",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'rap',
        name: "说唱",
        enable: true,
        bigCat: 'style',
    },
    {
        code: 'lightMusic',
        name: "轻音乐",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'sir',
        name: "爵士",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'country',
        name: "乡村",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'R&B/Soul',
        name: "R&B/Soul",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'classical',
        name: "古典",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'nation',
        name: "民族",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'british',
        name: "英伦",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'metal',
        name: "金属",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'punk',
        name: "朋克",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'blues',
        name: "蓝调",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'reggae',
        name: "雷鬼",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'worldMusic',
        name: "世界音乐",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'latin',
        name: "拉丁",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'newAge',
        name: "New Age",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'ancientry',
        name: "古风",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'rockBack',
        name: "后摇",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'bossaNova',
        name: "Bossa Nova",
        enable: false,
        bigCat: 'style',
    },
    {
        code: 'earlyMorning',
        name: "清晨",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'night',
        name: "夜晚",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'learn',
        name: "学习",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'work',
        name: "工作",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'siesta',
        name: "午休",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'afternoonTea',
        name: "下午茶",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'subway',
        name: "地铁",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'drive',
        name: "驾车",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'movement',
        name: "运动",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'travel',
        name: "旅行",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'takeAWalk',
        name: "散步",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'bar',
        name: "酒吧",
        enable: false,
        bigCat: 'scenes',
    },
    {
        code: 'reminiscence',
        name: "怀旧",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'fresh',
        name: "清新",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'romantic',
        name: "浪漫",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'sad',
        name: "伤感",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'cure',
        name: "治愈",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'relax',
        name: "放松",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'lonely',
        name: "孤独",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'move',
        name: "感动",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'beExcited',
        name: "兴奋",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'happy',
        name: "快乐",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'quiet',
        name: "安静",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'miss',
        name: "思念",
        enable: false,
        bigCat: 'emotion',
    },
    {
        code: 'varietyShow',
        name: "综艺",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'filmAndTelevisionSoundtrack',
        name: "影视原声",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'ACG',
        name: "ACG",
        enable: true,
        bigCat: 'theme',
    },
    {
        code: 'child',
        name: "儿童",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'campus',
        name: "校园",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'game',
        name: "游戏",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'post-70s',
        name: "70后",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'post-80s',
        name: "80后",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'post-90s',
        name: "90后",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'internetSongs',
        name: "网络歌曲",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'KTV',
        name: "KTV",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'classic',
        name: "经典",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'cover',
        name: "翻唱",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'guitar',
        name: "吉他",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'piano',
        name: "钢琴",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'instrumentalMusic',
        name: "器乐",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'list',
        name: "榜单",
        enable: false,
        bigCat: 'theme',
    },
    {
        code: 'post-00s',
        name: "00后",
        enable: false,
        bigCat: 'theme',
    },
];
